### ISSUE TITLE
Support Bamboo 5.11.1.1

### ISSUE THREAD

**Issue by testzugang** [alienfast/bamboozled-ruby-plugin#17]
Installing the plugin in Bamboo 5.11.1.1 leads to an error before the installation finishes.

**Comment by rosskevin** [comment]
Perhaps you would provide some details, like a log or a stack trace.

**Comment by testzugang** [comment]
The failure was shown on Bamboo with a hint to look into the logs for more details but when I checked the catalina.out log I did not find anything regarding this (or another) error. I tried to install using the jar as well as the URL for installing the plugin a few times and the number of error messages increased everytime.
When I checked the installed Bamboo plugins now again after about an hour the Bamboozled plugin is listed as installed but of course marked as incompatible. I will try to use it and see if there are other issues except the misleading installation error message.

**Comment by rosskevin** [comment]
I just updated compatibility in the marketplace to 5.11.1.1.  Please try and install from there, and provide that log if it errors.
