### ISSUE TITLE
--debug flag is not valid for capistrano3

### ISSUE THREAD

**Issue by i-ekho** [alienfast/bamboozled-ruby-plugin#4]
should use --trace

**Comment by rosskevin** [comment]
@i-ekho I'll have a release shortly, still working out some kinks.  If you can check it and give feedback while I've got my dev environment up and running I can likely get it fixed up for you.  Here's a pre-release jar: https://www.dropbox.com/s/bvh8qhh5ismg5b1/bamboozled-ruby-plugin-5.7.2.jar?dl=0
