### ISSUE TITLE
Capability detection on remote agents.

### ISSUE THREAD

**Issue by olisun** [alienfast/bamboozled-ruby-plugin#5]
I have installed and setup rbenv capabilities for my agents and for the master with the same path.

When I run the build on the remote agent I get the following error but when I run the job on the local agent it works fine.

```java
Error occurred while running Task '(3)' of type com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin:task.bundler.install.
java.lang.NullPointerException: Capability
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
        at com.alienfast.bamboozled.ruby.tasks.AbstractRubyTask.getRubyExecutablePath(AbstractRubyTask.java:156)
        at com.alienfast.bamboozled.ruby.tasks.AbstractRubyTask.buildEnvironment(AbstractRubyTask.java:177)
        at com.alienfast.bamboozled.ruby.tasks.AbstractRubyTask.execute(AbstractRubyTask.java:78)
        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:220)
        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:98)
        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:75)
        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:188)
        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:112)
        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:110)
        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by Jimflip** [comment]
Hi

So does this plugin work with remote agents or not (sorry I'm not sure what the outcome of the prior conversation is)?

**Comment by olisun** [comment]
It does ONLY if automatic capabilities detection is enabled in Bamboo but automatic capabilities detection leads to other problems in Bamboo.

**Comment by Jimflip** [comment]
Okay, thanks for clarifying.

**Comment by iiro** [comment]
To my understanding the agent's have an open bug which means you cannot disable the automatic detection at the moment.

But yes - I can confirm as well that the plugin works perfectly with remote agents; all I had to do is only install RVM to agents (as we are using Chef - I used RVM cookbook with subrecipe system_install).

I am having a problem with HOME directory though; I'm running Chef's knife in a job and it's giving me this:

error	22-Jan-2015 13:43:45	/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.1/lib/berkshelf.rb:71:in `expand_path': non-absolute home (ArgumentError)

It was working fine when I was using a plain Rake in custom cmd + had defined HOME in run; but if I try do that here I will get errors of duplicate HOMEs set. Anyone has any ideas? I can create another issue about this - but it sounds a bit more like knife's problem.

**Comment by rosskevin** [comment]
all- I'm making some additions/updates including xvfb-run.  While I have my dev environment going, if there I something I can do to accomodate remote agents, please let me know.  Since I'm not running them, I don't quite discern what is needed (if anything).

**Comment by kirvin** [comment]
We are running into the same problem with our Bamboo configuration (local agents detect capabilities and run tasks correctly; remote agents have the same ruby / gemset installations but fail during capability detection).

Our experience is the same as @olisun:  there is no way to manually define a capability with the Type property set to "Ruby".  The closest you can do is Type "Command", which then causes the check to fail on the remote agent.

Which leads me to this question:  is it possible for plugins to add new options to the "Type" list?  If so, this might fix the issue.  Otherwise, it appears that the only way to get a capability with type "Ruby" to appear is via the "Detect server capabilities" feature on the master node.  As others have pointed out, this only affects local agents.

@olisun:  do you have a link to the Jira ticket you filed with Atlassian?  For what it's worth, upvotes there might help getting this resolved...

**Comment by rosskevin** [comment]
> is it possible for plugins to add new options to the "Type" list?

My uneducated guess is that it is probably possible.  Pull requests are welcome.

**Comment by kmwhite** [comment]
I'm not a Java dev, but my research has pointed me to https://developer.atlassian.com/display/BAMBOODEV/Capability+Type+Module . If I can get it figured out, I'll attempt a PR.

**Comment by kmwhite** [comment]
Given my cursory searches, I found [this](https://developer.atlassian.com/display/BAMBOODEV/Capability+Type+Module) doc regarding Server Capability Types in Bamboo. I'll give it a go to see if it'll be simple to define a custom type from the drop down, but I make no promises; I don't often write Java code.

The biggest allure of this doc is:

> The Capability Type Module is used for registering custom capabilities for your Bamboo plugin.
> 
> You may want to use this module to:
> 
> * Provide a human readable name for your plugins capability
> * Provide custom template for editing the capability
> * Group multiple yet related capabilities. For example, Bamboo uses this module for its Mercurial support to define both the Mercurial and SSH executables used by Mercurial

The plugin doesn't currently have it defined in the XML, so hopefully that'll be a good enough starting point for it.

**Comment by rosskevin** [comment]
This will help you get setup: https://github.com/alienfast/bamboozled-ruby-plugin/wiki/Development

**Comment by sam2themax** [comment]
It looks like this commit on a fork might solve the issue:
https://github.com/Jimflip/bamboozled-ruby-plugin/commit/14f8641a08be8f5ca177c3c5d4874dbb85ae190c

**Comment by kirvin** [comment]
@Jimflip I ported your changes into my own fork and updated slightly to be compatible with `master` in this repo:  https://github.com/kirvin/bamboozled-ruby-plugin/tree/feature/remote-capability-detection.  Other changes in my branch were made to bring in third-party repos and fix some eclipse build issues.

I can confirm that your changes work on our remote agents.  Thanks for putting a solution together!

**Comment by rosskevin** [comment]
@kirvin @Jimflip @sam2themax

I'm looking at @Jimflip's changes and @sam2themax in #9.  It seems like @Jimflip's changes are simplest and work with the ruby capability.  Do you guys agree?  

@sam2themax, does yours cover Jim's change and add 'command'?

Do we need to add 'command' manual capability if we use Jim's code?

**Comment by rosskevin** [comment]
@kirvin I don't think you need https://github.com/kirvin/bamboozled-ruby-plugin/commit/652a7ab680db906fb6885a49abf233a948a30719 if you are using Atlassian's SDK and `atlas-mvn` for your commands.

**Comment by kirvin** [comment]
@rosskevin I'm sure you're right--I don't have the Atlassian SDK installed on our Bamboo server, so it was more straightforward to get it working this way for testing out the patch.

**Comment by sam2themax** [comment]
@rosskevin I ran into some strange behavior with local agents in my changes -- yes, the other approach is simpler so I'll decline my PR.

**Comment by rosskevin** [comment]
Guys, I've got a remote agent authenticated and running, and I have @Jimflip's code integrated and deployed.  It works with a local agent, no problem.  

I'm a bit confused on remote agent configuration; I expected my remote agent to show as an option under `admin | Agents`, and while I see my agent as both `online` and `authenticated`, I have no way to assign jobs to it on `Agent matrix` as it seems inactive.

Are you guys performing additional remote agent configuration to make it eligible for use in the matrix?  I've not added any capabilities manually on the agent side, and didn't do any additional configuration on the server other than to make sure the agent is connected.

**Comment by rosskevin** [comment]
@Jimflip  @kirvin  @sam2themax 

Are you guys using `bamboo-capabilities.properties` on your agents or shared?

**Comment by rosskevin** [comment]
Latest workaround jar is available via UPM, I'm still looking at capability types to make this easier.

**Comment by rosskevin** [comment]
Gentlemen - I've implemented capability types for both `xvfb-run` and `ruby`, you can now configure shared capability types for remote agents.  As of yet, I don't have my remote agent working, but please take an opportunity to try out this code.

1. Manually update plugin by uploading this jar: https://www.dropbox.com/s/maxzafo9o4d0feu/bamboozled-ruby-plugin-5.10.0.jar?dl=0
2. Restart your bamboo instance (my UPM game me an error, so I restarted to be safe)
3. Go to server capabilities and delete old xvfb-run from the `Executables` section
4. Detect server capabilities to re-establish xvfb-run
5. Try out your local agent builds (should be unaffected)
6. Add shared capabilities with type 'ruby' and test on remote agents

If this fails, uninstall plugin, and add again from the marketplace.

This worked fine for local builds, and it does have @Jimflip's workaround, but I think configuring shared capabilities of the `ruby` type has a chance to work now.

**Comment by rosskevin** [comment]
I had to open my ufw for 54663/tcp to get through, my remote agent is registered.  Auto detection on the remote seems to have worked fine, I set up the remote agent the same as the primary regarding paths.

**Comment by rosskevin** [comment]
No feedback from the group, but auto detection on the remote agent is working well for me.  Latest is available via UPM.  Release notes here: https://marketplace.atlassian.com/plugins/com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin/versions#b51

**Comment by kirvin** [comment]
@rosskevin Thanks for the new build--we'll try out this update early next week.

**Comment by sam2themax** [comment]
@rosskevin Was out for a couple days at the end of last week, but we'll give it a try this week, too.  Thanks for getting this out.

**Comment by Jimflip** [comment]
@rosskevin Hi sorry, just back from my holidays.
The fork I did was just a quick hack, I didn't have the time to delve further.
I'll give this fix a run in our system, and report back any issues.

Thanks.

**Comment by rosskevin** [comment]
Here are my notes on remote agents:

https://github.com/alienfast/bamboozled-ruby-plugin/wiki/Remote-Agents

Please feel free to add/edit

**Comment by sam2themax** [comment]
Looks good to me -- also, the plugin is working well with our remote agents now.  Many thanks!
