### ISSUE TITLE
bundle --package suppport

### ISSUE THREAD

**Issue by kirvin** [alienfast/bamboozled-ruby-plugin#8]
I would like to open a discussion around support for `bundle --package` support for this plugin.  Our delivery cycle looks like this:
*  Check out app source code
*  Use plugin to run `bundle install`
*  Run specs using gems in local directory (`vendor/bundle` by default?)
*  Run `bundle --package` to grab all gems (from rubygems, git repos, and internal gem server) and put in a local directory
*  Package entire app tree (source code, gems, etc.) into a single archive and push to distribution repository for later deployment

We currently use a patched version of rake-bamboo-plugin (https://github.com/wolfeidau/rake-bamboo-plugin) to accomplish this, but I would like to migrate to this plugin instead.

Is this a use case for anyone else?  If so, how are you handling it?

References
  1.  http://stackoverflow.com/questions/6300613/whats-the-difference-between-bundle-install-deployment-and-bundle-pack
  2.  http://bundler.io/bundle_package.html
  3.  http://bundler.io/v1.9/bundle_install.html

**Comment by rosskevin** [comment]
It should have `bundle --package` support, does the Bundler CLI task not work?  [Bundler CLI](https://github.com/alienfast/bamboozled-ruby-plugin#bundler-cli) should be able to handle the `--package` command if you want to use that method. 

For our app packaging, I use/maintain the [elastic-beanstalk gem](https://github.com/alienfast/elastic-beanstalk) which has a [rake task for putting together a zip](https://github.com/alienfast/elastic-beanstalk/blob/master/lib/elastic/beanstalk/tasks/eb.rake#L219).  In that environment, I do not bundle gems together, I allow the elastic beanstalk instance to pull it's own based on the `Gemfile.lock`.

**Comment by rosskevin** [comment]
No response, I can only assume that the Bundler CLI task works, if not please reopen.
